### ISSUE TITLE
BUG: Advanced Yaml anchors stopped working

### ISSUE THREAD

**Issue by laszlocph** [laszlocph/woodpecker#103]
since the go modules change in v0.8.106 the bellow pattern cause `Invalid or missing image`

```
  slack: &slack
    image: plugins/slack
    channel: team-xx
    secrets: [ slack_webhook ]


  slack-staging-deploy:
    <<: *slack
```
