### ISSUE TITLE
DOCS: Deployment guide for Kubernetes

### ISSUE THREAD

**Issue by laszlocph** [laszlocph/woodpecker#108]

**Comment by sudip-moengage** [comment]
@laszlocph Is there any draft I can use? We use to run woodpecker on a standalone setup. Now, I am migrating it to kuberntes. The dashboard is up. But pipeline failing at clone step saying `could not resolve github.com`. 

What am I missing?

**Comment by laszlocph** [comment]
Hm, sounds like a DNS issue. Can you resolve domain names, access the internet from other containers?

**Comment by sudip-moengage** [comment]
@laszlocph Yes. But I'm not sure how build containers get spawned in kubernetes. Since they are not spawned as pods, NAT won't happen. Is there any other setup required for kubernetes. For example drone has kubernetes-runner

**Comment by laszlocph** [comment]
Now, I remember this issue.

Here is how I run the agent in Kubernetes in a DinD setup.
Let me know if it helps.

```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: woodpecker-agent
  namespace: tools
  labels:
    app: woodpecker-agent
spec:
  selector:
    matchLabels:
      app: woodpecker-agent
  replicas: 2
  template:
    metadata:
      annotations:
      labels:
        app: woodpecker-agent
    spec:
      containers:
      - name: agent
        image: laszlocloud/woodpecker-agent:v0.9.2
        imagePullPolicy: Always
        ports:
        - name: http
          containerPort: 3000
          protocol: TCP
        env:
          - name: DRONE_SERVER
            value: woodpecker.tools.svc.cluster.local:9000
          - name: DRONE_SECRET
            value: "xxx"
          - name: DOCKER_HOST
            value: tcp://localhost:2375
        resources:
          limits:
            cpu: 2
            memory: 2Gi
      - name: dind
        image: "docker:19.03.5-dind"
        env:
        - name: DOCKER_DRIVER
          value: overlay2
        - name: DOCKER_TLS_CERTDIR
          value: "" # due to https://github.com/docker-library/docker/pull/166 & https://gitlab.com/gitlab-org/gitlab-runner/issues/4512
        resources:
          limits:
            cpu: 1
            memory: 2Gi
        securityContext:
          privileged: true

```
