### ISSUE TITLE
${DRONE_COMMIT_MESSAGE} key not available on builds based off merge commits from gitea

### ISSUE THREAD

**Issue by PeterAlabaster** [laszlocph/woodpecker#144]
We have a notifier step which takes the `${DRONE_COMMIT_MESSAGE}` global environment variable, and passes it through to a plugin which dispatches the message to another platform.

This step runs on merges to master, so we have this block as part of the pipeline step:
```yml
pipeline:
  notify:
    when:
      status: [ success ]
      event: push
      branch: master
    ...
```
When we perform a standard merge commit on gitea (by clicking `Merge Pull Request`), the build fails entirely, with an error like: `yaml: line 12: did not find expected key` in the Woodpecker UI

The line it complains about is the line which the `notify` pipeline step starts.

If we click the dropdown and instead do a `Squash and Merge` in Gitea, the error does not occur.

Also, if i remove the env var passthrough for this pipeline step, the error does not occur

It looks as if maybe Woodpecker is not setting `${DRONE_COMMIT_MESSAGE}` when a standard merge occurs
