### ISSUE TITLE
grpc error: done(): code: Unavailable: rpc error

### ISSUE THREAD

**Issue by earnestma** [laszlocph/woodpecker#166]
I am using Gitea v1.13.2

```
earne@oscean:~/gitea/ci$ sudo docker-compose up
Creating ci_woodpecker-server_1 ... done
Creating ci_woodpecker-agent_1  ... done
Attaching to ci_woodpecker-server_1, ci_woodpecker-agent_1
woodpecker-agent_1   | {"level":"debug","time":"2021-03-06T04:48:14Z","message":"request next execution"}
woodpecker-agent_1   | {"level":"debug","time":"2021-03-06T04:48:14Z","message":"request next execution"}
woodpecker-agent_1   | {"level":"debug","time":"2021-03-06T04:48:14Z","message":"request next execution"}
woodpecker-agent_1   | {"level":"debug","time":"2021-03-06T04:48:14Z","message":"request next execution"}
woodpecker-agent_1   | {"level":"debug","time":"2021-03-06T04:48:14Z","message":"request next execution"}
woodpecker-server_1  | time="2021-03-06T04:48:13Z" level=fatal msg="version control system not configured"
ci_woodpecker-server_1 exited with code 1
woodpecker-server_1  | time="2021-03-06T04:48:13Z" level=fatal msg="version control system not configured"
woodpecker-server_1  | time="2021-03-06T04:48:15Z" level=fatal msg="version control system not configured"
woodpecker-server_1  | time="2021-03-06T04:48:15Z" level=fatal msg="version control system not configured"
ci_woodpecker-server_1 exited with code 1
woodpecker-server_1  | time="2021-03-06T04:48:13Z" level=fatal msg="version control system not configured"
woodpecker-server_1  | time="2021-03-06T04:48:15Z" level=fatal msg="version control system not configured"
woodpecker-server_1  | time="2021-03-06T04:48:15Z" level=fatal msg="version control system not configured"
woodpecker-server_1  | time="2021-03-06T04:48:16Z" level=fatal msg="version control system not configured"
woodpecker-agent_1   | 2021/03/06 04:48:18 grpc error: done(): code: Unavailable: rpc error: code = Unavailable desc = connection error: desc = "transport: Error while dialing dial tcp 172.19.0.3:9000: connect: no route to host"
woodpecker-agent_1   | 2021/03/06 04:48:18 grpc error: done(): code: Unavailable: rpc error: code = Unavailable desc = connection error: desc = "transport: Error while dialing dial tcp 172.19.0.3:9000: connect: no route to host"
woodpecker-agent_1   | 2021/03/06 04:48:18 grpc error: done(): code: Unavailable: rpc error: code = Unavailable desc = connection error: desc = "transport: Error while dialing dial tcp 172.19.0.3:9000: connect: no route to host"
woodpecker-agent_1   | 2021/03/06 04:48:18 grpc error: done(): code: Unavailable: rpc error: code = Unavailable desc = connection error: desc = "transport: Error while dialing dial tcp 172.19.0.3:9000: connect: no route to host"
woodpecker-agent_1   | 2021/03/06 04:48:18 grpc error: done(): code: Unavailable: rpc error: code = Unavailable desc = connection error: desc = "transport: Error while dialing dial tcp 172.19.0.3:9000: connect: no route to host"
```

.env:
```
DRONE_SECRET=...
DRONE_ADMIN=earnestma
DRONE_GITEA_CLIENT_ID=...
DRONE_GITEA_CLIENT_SECRET=...
```

my docker-compose.yml file:
```
version: '3'

services:
  woodpecker-server:
    image: laszlocloud/woodpecker-server:v0.12.0
    ports:
      - 8000:8000
      - 9000
    volumes:
      - woodpecker-server-data:/var/lib/drone/
    restart: always
    environment:
      - DRONE_OPEN=true
      - DRONE_HOST=https://ci.earne.link
      - DRONE_SECRET=${DRONE_SECRET}
      - DRONE_ADMIN=${DRONE_ADMIN}
      - DRONE_GITEA_CLIENT_ID=${DRONE_GITEA_CLIENT_ID}
      - DRONE_GITEA_CLIENT_SECRET=${DRONE_GITEA_CLIENT_SECRET}

  woodpecker-agent:
    image: laszlocloud/woodpecker-agent:v0.12.0
    command: agent
    restart: always
    depends_on:
      - woodpecker-server
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - DRONE_SERVER=woodpecker-server:9000
      - DRONE_SECRET=${DRONE_SECRET}
      - DRONE_MAX_PROCS=5 # default is 4

volumes:
  woodpecker-server-data:
```

nginx reverse proxy file:
```
server {
    server_name ci.earne.link;

    location / {
        proxy_set_header X-Forwarded-For $remote_addr;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_set_header Host $http_host;

        proxy_pass http://127.0.0.1:1999;
        proxy_redirect off;
        proxy_http_version 1.1;
        proxy_buffering off;

        chunked_transfer_encoding off;
    }

    listen 443 ssl;
    ssl_certificate /etc/letsencrypt/live/ci.earne.link/fullchain.pem; # managed by Certbot
    ssl_certificate_key /etc/letsencrypt/live/ci.earne.link/privkey.pem;
    include /etc/letsencrypt/options-ssl-nginx.conf;
    ssl_dhparam /etc/letsencrypt/ssl-dhparams.pem;

}
server {
    if ($host = ci.earne.link) {
        return 301 https://$host$request_uri;
    }

    listen 80;
    server_name ci.earne.link;
    return 404;
}
```
