### ISSUE TITLE
Help with k8s faulty deployment

### ISSUE THREAD

**Issue by mariusrugan** [laszlocph/woodpecker#190]
hi, 

am using the example deployment in docs, upgraded to the latest image version available,
and stripped down to bare Deployment/Service, the pod starts but no connectivity to it is available. (for example port fw to 8000)

seems the DEBUG flag is not picked up, i've tried all kinds of combos from drone / woodpecker docs (as per below)

Am using nfs-client pvc, the volume is created, for example: 
```
apps-woodpecker-pvc-pvc-fb557d9d-96c3-463e-8829-7e1dd6aaabc4
```
however i have a zero size drone.sqlite inside.

am deploying on a functional k3s cluster, other apps use the same-style, nfs-client pv/pvc combos, disk is writable.

```
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: woodpecker
  namespace: apps
  labels:
    app: woodpecker
spec:
  replicas: 1
  selector:
    matchLabels:
      app: woodpecker
  template:
    metadata:
      labels:
        app: woodpecker
      annotations:
        prometheus.io/scrape: 'true'
    spec:
      containers:
      - image: laszlocloud/woodpecker-server:v0.13.0-rc.3
        imagePullPolicy: Always
        name: woodpecker
        env:
        - name: "DRONE_LOGS_DEBUG"
          value: "true"
        - name: "DRONE_DEBUG"
          value: "true"
        - name: "DRONE_GITHUB"
          value: "true"
        - name: "DRONE_HOST"
          value: "https://woodpecker.example.com"
        - name: "DRONE_ADMIN"
          value: "root"
        - name: "DRONE_SECRET"
          value: "##REDACTED##"
        - name: "DRONE_GITHUB"
          value: "true"
        - name: "DRONE_GITHUB_CLIENT"
          value: "##REDACTED##"
        - name: "DRONE_GITHUB_SECRET"
          value: "##REDACTED##"
        - name: "WOODPECKER_DEBUG"
          value: 'true'
        volumeMounts:
          - name: sqlite-volume
            mountPath: /var/lib/drone
      volumes:
        - name: sqlite-volume
          persistentVolumeClaim:
            claimName: woodpecker-pvc
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: woodpecker-pvc
  namespace: apps
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: nfs-client
  resources:
    requests:
      storage: 1Gi
  volumeMode: Filesystem
---
kind: Service
apiVersion: v1
metadata:
  name: woodpecker
  namespace: apps
spec:
  type: ClusterIP
  selector:
    app: woodpecker
  ports:
  - protocol: TCP
    name: http
    port: 8000
    targetPort: 8000
  - protocol: TCP
    name: grpc
    port: 9000
    targetPort: 9000
```
